src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Colour__c</fullName>
        <label>Colour</label>
        <picklist>
            <picklistValues>
                <fullName>Black</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SimpleCar.cls
public class SimpleCar
{
	public static final Set<String> allowedColours = new Set<String>{'RED','WHITE'};

	public Car__c myCar;

	 public SimpleCar(Id carId)
	 {
	 	myCar = [SELECT Id, Name, Colour__c FROM Car__c where Id = :carId];
	 }

	 public String getColour()
	 {
	 	return myCar.Colour__c;
	 }

	 public void setColour(String colour)
	 {
	 	if (!allowedColours.contains(colour))
	 		throw new VehicleException('Wrong Colour');

	 	try
	 	{
	 		myCar.Colour__c = colour;
	 		update myCar;
	 	}
	 	catch (Exception e)
	 	{
	 		System.debug('Update failed');
	 	}
	 }
}