src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RentHours__c</fullName>
        <label>RentHours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rented__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rented</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RentingPrice__c</fullName>
        <label>Renting Price / Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sold</label>
        <type>Checkbox</type>
    </fields>
    <label>Car</label>
    <nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Car Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRAN-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Car.cls
public class Car
{
	// Property
	public Car__c Dto { get; set;}

	// Instance variable
	private static final List<String> fields = Utilities.getSObjectFields('Car__c');

	public Car()
	{
		Dto = new Car__c();
	}

	public Car(Id carId)
	{
		// Dynamic SOQL
		Dto = Database.query('SELECT ' + Utilities.getFieldListAsString(fields) + ' FROM Car__c where Id = :carId');
	}

	public void sell()
	{
		Savepoint sp = Database.setSavepoint();

		try
		{
			if ((boolean) Dto.Sold__c == false)
			{
				// Update sold checkbox
				Dto.Sold__c = true;
				update Dto;

				// Add transaction
				Decimal amount = (Decimal) Dto.Price__c;
				Transaction__c transact = new Transaction__c();
				transact.Amount__c = amount;
				insert transact;
			}
		}
		catch (Exception e)
		{
			Dto.Sold__c = false;
			Database.rollback(sp);
			throw e;
		}
	}

	public void rent()
	{
		Savepoint sp = Database.setSavepoint();

		try
		{
			if ((boolean) Dto.Rented__c == false)
			{
				// Update rent hours and rented checkbox
				Dto.Rented__c = true;
				update Dto;

				// Add transaction
				Decimal pricePerHour = (Decimal) Dto.RentingPrice__c;
				Decimal amount = pricePerHour * (Decimal) Dto.RentHours__c;
				Transaction__c transact = new Transaction__c();
				transact.Amount__c = amount;
				insert transact;
			}
		}
		catch (Exception e)
		{
			Dto.Rented__c = false;
			Database.rollback(sp);
			throw e;
		}
	}

	public void returnRentedVehicle()
	{
		if ((boolean) Dto.Rented__c == true)
		{
			// Update rent hours and rented checkbox
			Dto.Rented__c = false;
			Dto.RentHours__c = null;
			update Dto;
		}
	}

	public PageReference getViewPage()
	{
		return new ApexPages.StandardController(Dto).view();
	}
}